/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "oryghovnkhdouiishsfx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yeWdob3Zua2hkb3VpaXNoc2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2Mzk4ODYsImV4cCI6MjA3OTIxNTg4Nn0.h39BW0lDbad3CLId-OVkDND4mrVn06G7-Q1MEyq-7ts"